apiVersion: v1
kind: BuildConfig
metadata:
  name: timeservice-buildconfig
  labels:
    name: timeservice-buildconfig
spec:
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/torstenatgithub/time-service
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
