apiVersion: v1
kind: Template
labels:
  template: ergo-openjdk18-binary-s2i
  application: "${APPLICATION_NAME}"
message: A new java application has been created in your project.
metadata:
  annotations:
    description: >-
      Based on the OpenJDK 8 template by Red Hat, modified for binary source.
      For more information about using this template, see https://github.com/jboss-openshift/application-templates.
    iconClass: icon-openjdk
    openshift.io/display-name: OpenJDK 8
    openshift.io/provider-display-name: ERGO
    tags: "java,ergo"
    template.openshift.io/documentation-url: https://access.redhat.com/documentation/en/
    template.openshift.io/long-description: This template defines resources needed to develop OpenJDK Java 8 based applications.
    template.openshift.io/support-url: https://access.redhat.com
    version: 1.0
  name: ergo-openjdk18-binary-s2i
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The application's http port.
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: 8080-tcp
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    name: "${APPLICATION_NAME}"
  spec:
    host: "${HOSTNAME_HTTP}"
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Target ImageStream for the application's build.
    name: "${APPLICATION_NAME}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: BuildConfig for the application.
    name: "${APPLICATION_NAME}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
    source:
      type: Binary
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: "openjdk18-openshift:latest"
          namespace: "${SOURCE_IMAGE_STREAM_NAMESPACE}"
      type: Source
    runPolicy: Serial
    triggers:
    - github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
      type: GitHub
    - generic:
        secret: "${GENERIC_WEBHOOK_SECRET}"
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: DeploymentConfig for the application.
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: "${APPLICATION_NAME}"
          application: "${APPLICATION_NAME}"
          deploymentConfig: "${APPLICATION_NAME}"
        name: "${APPLICATION_NAME}"
      spec:
        containers:
        - env: []
          image: "${APPLICATION_NAME}"
          imagePullPolicy: Always
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APPLICATION_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}:latest"
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: openjdk-app
- description: >-
    Custom hostname for http service route.
    Leave blank for default hostname, e.g. <application-name>-<project>.<default-domain-suffix>
  displayName: Custom http Route Hostname
  name: HOSTNAME_HTTP
  required: false
  value: ''
- description: GitHub trigger secret.
  displayName: Github Webhook Secret
  from: "[a-zA-Z0-9]{12}"
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
  required: true
- description: Generic build trigger secret.
  displayName: Generic Webhook Secret
  from: "[a-zA-Z0-9]{12}"
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
- description: >-
    Namespace in which the ImageStreams for builder images are installed.
    These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
  displayName: ImageStream Namespace
  name: SOURCE_IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift