apiVersion: v1
kind: DeploymentConfig
metadata:
  name: time-service
  labels:
    app: time-service
spec:
  template:
    metadata:
      labels:
        name: time-service
    spec:
      containers:
        - image: time-service-dev/time-service
          name: time-service
          ports:
            - containerPort: 8080
              protocol: TCP
  replicas: 1
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - test-service
        from:
          kind: ImageStreamTag
          name: 'time-service:latest'
      type: ImageChange
    - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
