apiVersion: v1
kind: DeploymentConfig
metadata:
  name: time-service
  labels:
    app: time-service
spec:
  selector:
    deploymentconfig: time-service
  template:
    metadata:
      labels:
        name: time-service
        deploymentconfig: time-service
    spec:
      containers:
        - image: >-
            172.30.1.1:5000/time-service-dev/time-service@sha256:1f51710eddf48c3f3925529a1a7827801dcc9be5cc84d18b81eac7ab404485ba
          name: time-service
          ports:
            - containerPort: 8080
              protocol: TCP
  replicas: 1
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - test-service
        from:
          kind: ImageStreamTag
          name: 'time-service:latest'
      type: ImageChange
    - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
