apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: time-service
  name: time-service
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'time-service:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'redhat-openjdk18-openshift:latest'
        namespace: openshift
    type: Source
  triggers:
    - type: ConfigChange
